nav:
  - Lamp of Malice Guide: './events/lamp-of-malice/lamp-of-malice-text-guide.md'
  - Old Castle Ruins Guide: './events/old-castle-ruins/old-castle-ruins-guide.md'
  - Labyrinth of Fordraig Guide: './events/labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
  - Pixie and the Secret Garden Guide: './events/pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
  - Otherworld Adventurers Guide: './events/otherworld-adventurers/otherworld-adventurers-guide.md'
  - Fighter Proving Grounds Guide: './events/fighter-proving-grounds/fighter-proving-grounds-guide.md'
