nav:
  - Introduction: './abyss-guides/0-introduction/index.md'
  - Beginning Abyss:
      - Maps: './abyss-guides/1-beginning-abyss/maps.md'
      - Requests: './abyss-guides/1-beginning-abyss/requests.md'
      - Important Request / Greater Warped One: './abyss-guides/1-beginning-abyss/important-request-gwo.md'
  - Port Town Grand Legion:
      - Maps: './abyss-guides/2-port-town-grand-legion/maps.md'
      - Requests: './abyss-guides/2-port-town-grand-legion/requests.md'
      - Important Request / Greater Warped One: './abyss-guides/2-port-town-grand-legion/important-request-gwo.md'
  - Guarda Fortress:
      - Maps: './abyss-guides/3-guarda-fortress/maps.md'
      - Requests: './abyss-guides/3-guarda-fortress/requests.md'
      - Important Request / Greater Warped One: './abyss-guides/3-guarda-fortress/important-request-gwo.md'
  - Ancient Mausoleum: './abyss-guides/ancient-mausoleum/maps.md'
  - Dens:
      - Den of Earth: './abyss-guides/dens/den-of-earth.md'
      - Den of Fire: './abyss-guides/dens/den-of-fire.md'
      - Den of Wind: './abyss-guides/dens/den-of-wind.md'
      - Den of Light: './abyss-guides/dens/den-of-light.md'
  - Grade Exams: './abyss-guides/grade-exams/maps.md'
  - Misc Bosses:
      - Morgus, God of Death: './abyss-guides/misc-bosses/morgus-god-of-death.md'
