site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.footnote.tooltips
    - search.suggest
markdown_extensions:
  - toc:
      toc_depth: 4
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
  - search
extra_css:
  - stylesheets/table.css
  - stylesheets/style.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.number.js
  - javascripts/tablesort.js

nav:
  - Quick Reference: './quick-reference.md'
  - FAQ: './frequently-asked-questions.md'
  - Maps:
      - Beginning Abyss: './maps/beginning-abyss.md'
      - Trade Waterways: './maps/trade-waterways.md'
      - Den of Earth: './maps/den-of-earth.md'
      - Den of Fire: './maps/den-of-fire.md'
      - Den of Wind: './maps/den-of-wind.md'
  - Story:
      - Act 1 - Beginning Abyss:
        - Main Story: './story/1-beginning-abyss/main-story.md'
        - Requests/Bondmates: './story/1-beginning-abyss/requests-bondmates.md'
      - Act 2 - Port Town Grand Legion:
        - Main Story: './story/2-port-town-grand-legion/main-story.md'
        - Requests/Bondmates: './story/2-port-town-grand-legion/requests-bondmates.md'
  - Events:
      - Lamp of Malice:
        - Text Guide: './events/lamp-of-malice/lamp-of-malice-text-guide.md'
        - Video Guide: './events/lamp-of-malice/lamp-of-malice-video-guide.md'
  - Strategies:
      - Boss Guide: './strategies/Boss-guide.md'
      - Combat Strategies: './strategies/combat-strategies.md'
      - Party Construction: './strategies/party-construction.md'
      - Port Town Grand Legion: './strategies/port-town-grand-legion.md'
      - Powerleveling: './strategies/powerleveling.md'
  - Skills:
      - Passive Skills: './skills/passive-skills.md'
      - Active Skills: './skills/active-skills.md'
      - Offensive Spells: './skills/offensive-spells.md'
      - Debuff Spells: './skills/debuff-spells.md'
      - Support Spells: './skills/support-spells.md'
  - Blacksmithing: './blacksmithing.md'
  - Grade Up: './grade-up/grade-up.md'
  - Trust:
    - Trust Guide: './trust/trust.md'
    - Dialogue Chart: './trust/chart.md'
  - Guiding Light: './guiding-light.md'
  - Well of the Mind: './well-of-the-mind.md'
  - Adventurer's Life Stories:
    - Legendary Adventurer:
      - Adam: './adventurer_life_stories/legendary_adventurer/Adam.md'
      - Alice: './adventurer_life_stories/legendary_adventurer/Alice.md'
      - Debra: './adventurer_life_stories/legendary_adventurer/Debra.md'
      - Gerard: './adventurer_life_stories/legendary_adventurer/Gerard.md'
      - Gerulf: './adventurer_life_stories/legendary_adventurer/Gerulf.md'
      - Lanavaille: './adventurer_life_stories/legendary_adventurer/Lanavaille.md'
      - Yekaterina: './adventurer_life_stories/legendary_adventurer/Yekaterina.md'
    - Non Legendary Adventurer:
      - Alex: './adventurer_life_stories/non_legendary_adventurer/Alex.md'
      - Amelia: './adventurer_life_stories/non_legendary_adventurer/Amelia.md'
      - Asha: './adventurer_life_stories/non_legendary_adventurer/Asha.md'
      - Bakesh: './adventurer_life_stories/non_legendary_adventurer/Bakesh.md'
      - Barbara: './adventurer_life_stories/non_legendary_adventurer/Barbara.md'
      - Benjamin: './adventurer_life_stories/non_legendary_adventurer/Benjamin.md'
      - Chloe: './adventurer_life_stories/non_legendary_adventurer/Chloe.md'
      - Clarissa: './adventurer_life_stories/non_legendary_adventurer/Clarissa.md'
      - Daniel: './adventurer_life_stories/non_legendary_adventurer/Daniel.md'
      - Dino: './adventurer_life_stories/non_legendary_adventurer/Dino.md'
      - Eckart: './adventurer_life_stories/non_legendary_adventurer/Eckart.md'
      - Elda: './adventurer_life_stories/non_legendary_adventurer/Elda.md'
      - Eldorado: './adventurer_life_stories/non_legendary_adventurer/Eldorado.md'
      - Elise: './adventurer_life_stories/non_legendary_adventurer/Elise.md'
      - Emil: './adventurer_life_stories/non_legendary_adventurer/Emil.md'
      - Eulalia: './adventurer_life_stories/non_legendary_adventurer/Eulalia.md'
      - Flut: './adventurer_life_stories/non_legendary_adventurer/Flut.md'
      - Galina: './adventurer_life_stories/non_legendary_adventurer/Galina.md'
      - Gandolfo: './adventurer_life_stories/non_legendary_adventurer/Gandolfo.md'
      - Gaston: './adventurer_life_stories/non_legendary_adventurer/Gaston.md'
      - Jarmil: './adventurer_life_stories/non_legendary_adventurer/Jarmil.md'
      - Jean: './adventurer_life_stories/non_legendary_adventurer/Jean.md'
      - Marianne: './adventurer_life_stories/non_legendary_adventurer/Marianne.md'
      - Milana: './adventurer_life_stories/non_legendary_adventurer/Milana.md'
      - Olive: './adventurer_life_stories/non_legendary_adventurer/Olive.md'
      - Ophelia: './adventurer_life_stories/non_legendary_adventurer/Ophelia.md'
      - Phillip: './adventurer_life_stories/non_legendary_adventurer/Phillip.md'
      - Valdor: './adventurer_life_stories/non_legendary_adventurer/Valdor.md'
      - Viviana: './adventurer_life_stories/non_legendary_adventurer/Viviana.md'
  - Adventurer Reviews:
      - Adam: './adventurer-reviews/Adam.md'
      - Alice: './adventurer-reviews/Alice.md'
      - Debra: './adventurer-reviews/Debra.md'
      - Gerard: './adventurer-reviews/Gerard.md'
      - Gerulf: './adventurer-reviews/Gerulf.md'
      - Lanavaille:
          - Lanavaille: './adventurer-reviews/Lanavaille/Lanavaille.md'
          - Standard: './adventurer-reviews/Lanavaille/Lanavaille-Standard.md'
          - Wandering Princess: './adventurer-reviews/Lanavaille/Lanavaille-Wandering-Princess.md'
      - Yekaterina: './adventurer-reviews/Yekaterina.md'
  - Jeweler Package Evaluation: './jeweler-package-evaluation.md'
  - Enemy Compendium: './enemy-compendium.md'
  - About The Guide: './index.md'
