site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

nav:
  - Guide: 'index.md'
  - Story:
      - Act 1 - Beginning Abyss: './story/1-beginning-abyss/main-story.md'
      - Act 2 - Port Town Grand Legion: './story/2-port-torn-grand-legion/main-story.md'