site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  font:
    text: Zen Old Mincho
  logo: img/logo_red.webp
  favicon: img/favicon.ico
  features:
    - content.footnote.tooltips
    - search.suggest
extra:
  generator: false
markdown_extensions:
  - toc:
      toc_depth: 4
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
  - search
extra_css:
  - stylesheets/table.css
  - stylesheets/style.css
  - stylesheets/scheme.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.number.js
  - javascripts/tablesort.js

nav:
  - Quick Reference: './quick-reference.md'
  - FAQ: './frequently-asked-questions.md'
  - Adventurers:
    - Legendary Adventurers:
      - Adventurer Review Disclaimer: './adventurers/legendary-adventurers/reviews/_adventurer-review-disclaimer.md'
      - Adam:
        - Details: './adventurers/legendary-adventurers/details/Adam.md'
        - Review: './adventurers/legendary-adventurers/reviews/Adam.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Adam.md'
      - Alice:
        - Details: './adventurers/legendary-adventurers/details/Alice.md'
        - Review: './adventurers/legendary-adventurers/reviews/Alice.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Alice.md'
      - Debra:
        - Details: './adventurers/legendary-adventurers/details/Debra.md'
        - Review: './adventurers/legendary-adventurers/reviews/Debra.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Debra.md'
      - Gerard:
        - Details: './adventurers/legendary-adventurers/details/Gerard.md'
        - Review: './adventurers/legendary-adventurers/reviews/Gerard.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Gerard.md'
      - Gerulf:
        - Details: './adventurers/legendary-adventurers/details/Gerulf.md'
        - Review: './adventurers/legendary-adventurers/reviews/Gerulf.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Gerulf.md'
      - Lanavaille:
        - Details: './adventurers/legendary-adventurers/details/Lanavaille.md'
        - Standard Review: './adventurers/legendary-adventurers/reviews/Lanavaille-Standard.md'
        - Wandering Princess Review: './adventurers/legendary-adventurers/reviews/Lanavaille-Wandering-Princess.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Lanavaille.md'
      - Yekaterina:
        - Details: './adventurers/legendary-adventurers/details/Yekaterina.md'
        - Review: './adventurers/legendary-adventurers/reviews/Yekaterina.md'
        - Life Story: './adventurers/legendary-adventurers/life-stories/Lanavaille.md'
    - General Adventurers:
      - Alex:
        - Life Story: './adventurers/general-adventurers/life-stories/Alex.md'
      - Amelia:
        - Life Story: './adventurers/general-adventurers/life-stories/Amelia.md'
      - Asha: 
        - Life Story: './adventurers/general-adventurers/life-stories/Asha.md'
      - Bakesh:
        - Life Story: './adventurers/general-adventurers/life-stories/Bakesh.md'
      - Barbara: 
        - Life Story: './adventurers/general-adventurers/life-stories/Barbara.md'
      - Benjamin:
        - Life Story: './adventurers/general-adventurers/life-stories/Benjamin.md'
      - Chloe:
        - Life Story: './adventurers/general-adventurers/life-stories/Chloe.md'
      - Clarissa:
        - Life Story: './adventurers/general-adventurers/life-stories/Clarissa.md'
      - Daniel:
        - Life Story: './adventurers/general-adventurers/life-stories/Daniel.md'
      - Dino:
        - Life Story: './adventurers/general-adventurers/life-stories/Dino.md'
      - Eckart:
        - Life Story: './adventurers/general-adventurers/life-stories/Eckart.md'
      - Elda:
        - Life Story: './adventurers/general-adventurers/life-stories/Elda.md'
      - Eldorado:
        - Life Story: './adventurers/general-adventurers/life-stories/Eldorado.md'
      - Elise:
        - Life Story: './adventurers/general-adventurers/life-stories/Elise.md'
      - Emil:
        - Life Story: './adventurers/general-adventurers/life-stories/Emil.md'
      - Eulalia:
        - Life Story: './adventurers/general-adventurers/life-stories/Eulalia.md'
      - Flut:
        - Life Story: './adventurers/general-adventurers/life-stories/Flut.md'
      - Galina:
        - Life Story: './adventurers/general-adventurers/life-stories/Galina.md'
      - Gandolfo:
        - Life Story: './adventurers/general-adventurers/life-stories/Gandolfo.md'
      - Gaston:
        - Life Story: './adventurers/general-adventurers/life-stories/Gaston.md'
      - Jarmil:
        - Life Story: './adventurers/general-adventurers/life-stories/Jarmil.md'
      - Jean:
        - Life Story: './adventurers/general-adventurers/life-stories/Jean.md'
      - Marianne:
        - Life Story: './adventurers/general-adventurers/life-stories/Marianne.md'
      - Milana:
        - Life Story: './adventurers/general-adventurers/life-stories/Milana.md'
      - Olive:
        - Life Story: './adventurers/general-adventurers/life-stories/Olive.md'
      - Ophelia:
        - Life Story: './adventurers/general-adventurers/life-stories/Ophelia.md'
      - Phillip:
        - Life Story: './adventurers/general-adventurers/life-stories/Phillip.md'
      - Valdor:
        - Life Story: './adventurers/general-adventurers/life-stories/Valdor.md'
      - Viviana:
        - Life Story: './adventurers/general-adventurers/life-stories/Viviana.md'
  - Cursed Wheel:
    - Wheel Causality:
      - Beginning Abyss: './cursed-wheel/wheel-causality/beginning-abyss.md'
      - Port Town Grand Legion: './cursed-wheel/wheel-causality/port-town-grand-legion.md'
    - Important Requests and Greater Warped Ones:
      - Beginning Abyss: './cursed-wheel/important-requests-greater-warped-ones/beginning-abyss.md'
      - Port Town Grand Legion: './cursed-wheel/important-requests-greater-warped-ones/port-town-grand-legion.md'
  - Requests and Bondmates:
    - Bondmates Quicklist: './requests-bondmates/bondmates-quicklist.md'
    - Beginning Abyss: './requests-bondmates/beginning-abyss/requests-bondmates.md'
    - Port Town Grand Legion: './requests-bondmates/port-town-grand-legion/requests-bondmates.md'
    - Legendary Requests:
      - Gerulf - Collect on a Broken Pact: './requests-bondmates/legendary-requests/broken-pact/broken-pact.md'
  - Guiding Light: './guiding-light.md'
  - Well of the Mind: './well-of-the-mind.md'
  - Skills:
    - Passive Skills: './skills/passive-skills.md'
    - Active Skills: './skills/active-skills.md'
    - Offensive Spells: './skills/offensive-spells.md'
    - Debuff Spells: './skills/debuff-spells.md'
    - Support Spells: './skills/support-spells.md'
  - Strategies:
      - Boss Guide: './strategies/Boss-guide.md'
      - Combat Strategies: './strategies/combat-strategies.md'
      - Party Construction: './strategies/party-construction.md'
      - Port Town Grand Legion: './strategies/port-town-grand-legion.md'
      - Powerleveling: './strategies/powerleveling.md'
  - Trust:
    - Trust Guide: './trust/trust.md'
    - Dialogue Chart: './trust/chart.md'
  - Blacksmithing: './blacksmithing.md'
  - Grade Exams: './grade-up/grade-up.md'
  - Maps:
    - Beginning Abyss: './maps/beginning-abyss.md'
    - Trade Waterways: './maps/trade-waterways.md'
    - Ancient Mausoleum: './maps/ancient-mausoleum.md'
    - Den of Earth: './maps/den-of-earth.md'
    - Den of Fire: './maps/den-of-fire.md'
    - Den of Wind: './maps/den-of-wind.md'
  - Events:
    - Lamp of Malice:
      - Text Guide: './events/lamp-of-malice/lamp-of-malice-text-guide.md'
      - Video Guide: './events/lamp-of-malice/lamp-of-malice-video-guide.md'
  - Jeweler Package Evaluation: './jeweler-package-evaluation.md'
  - Enemy Compendium: './enemy-compendium.md'
  - About The Guide: './index.md'