site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

nav:

  - Quick Reference: './quick-reference.md'
  - Story:
      - Act 1 - Beginning Abyss:
        - Main Story: './story/1-beginning-abyss/main-story.md'
        - Requests/Bondmates: './story/1-beginning-abyss/requests-bondmates.md'
      - Act 2 - Port Town Grand Legion:
        - Main Story: './story/2-port-town-grand-legion/main-story.md'
        - Requests: './story/2-port-town-grand-legion/requests.md'
  - Skills: './skills/index.md'
  - Affinity: './affinity/index.md'
  - Equipment:
      - Blacksmithing: './equipment/blacksmithing.md'
  - Bondmates: './bondmates/index.md'
  - Guiding Light: './guiding-light.md'
  - Well of the Mind: './well-of-the-mind.md'
  - Character Reviews: './character-review/index.md'
  - Frequently Asked Questions: './faq.md'
  - Reference:
    - How much experience do I need to level up?
  -  About The Guide: './index.md'
