site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
extra_css:
  - stylesheets/table.css

nav:
  - Quick Reference: './quick-reference.md'
  - Maps:
      - Beginning Abyss: './maps/beginning-abyss.md'
      - Trade Waterways: './maps/trade-waterways.md'
      - Den of Earth: './maps/den-of-earth.md'
  - Story:
      - Act 1 - Beginning Abyss:
        - Main Story: './story/1-beginning-abyss/main-story.md'
        - Requests/Bondmates: './story/1-beginning-abyss/requests-bondmates.md'
      - Act 2 - Port Town Grand Legion:
        - Main Story: './story/2-port-town-grand-legion/main-story.md'
        - Requests: './story/2-port-town-grand-legion/requests.md'
  - Strategies:
      - Combat Strategies: './strategies/combat-strategies.md'
      - Party Construction: './strategies/party-construction.md'
  - Skills:
      - Passive Skills: './skills/passive-skills.md'
      - Active Skills: './skills/active-skills.md'
      - Offensive Spells: './skills/offensive-spells.md'
      - Debuff Spells: './skills/debuff-spells.md'
      - Support Spells: './skills/support-spells.md'
  - Blacksmithing: './blacksmithing.md'
  - Grade Up: './grade-up/grade-up.md'
  - Affinity: './affinity/index.md'
  - Bondmates: './bondmates/index.md'
  - Guiding Light: './guiding-light.md'
  - Well of the Mind: './well-of-the-mind.md'
  - Character Reviews:
      - Adam: './character-review/Adam.md'
      - Alice: './character-review/Alice.md'
      - Debra: './character-review/Debra.md'
      - Gerard: './character-review/Gerard.md'
      - Gerulf: './character-review/Gerulf.md'
      - Lanavaille: './character-review/Lanavaille.md'
      - Yekaterina: './character-review/Yekaterina.md'
  - Frequently Asked Questions: './frequently-asked-questions.md'
  - About The Guide: './index.md'
