site_name: Wizardry Variants Daphne - Community Guide
site_url: https://wizardry.fasterthoughts.io
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

nav:
  - Guide: './index.md'
  - Story:
      - Act 1 - Beginning Abyss: './story/1-beginning-abyss/main-story.md'
      - Act 2 - Port Town Grand Legion: './story/2-port-torn-grand-legion/main-story.md'

  - Basics (Coming Soon...): '#'
  - Classes: './classes/index.md'
  - Skills: './skills/index.md'
  - Affinity: './affinity/index.md'
  - Equipment: './equipment/index.md'
  - Bondmates: './bondmates/index.md'
  - Guiding Light: './guiding-light.md'
  - Well of the Mind: './well-of-the-mind.md'
  - Frequently Asked Questions: './faq.md'
  - Maps (Coming Soon...): '#'
  - Reference:
    - How much experience do I need to level up?
