nav:
  - Achievements: './appendices/achievements.md'
  - Cursed Wheel Causality:
      - Beginning Abyss: './appendices/wheel-causality/beginning-abyss.md'
      - Port Town Grand Legion: './appendices/wheel-causality/port-town-grand-legion.md'
      - Guarda Fortress: './appendices/wheel-causality/guarda-fortress.md'
  - Dispatches: './appendices/dispatches.md'
  - Equipment:
      - Weapon Types: './appendices/equipment/weapon-types.md'
      - Unique Equipment: './appendices/equipment/unique-equipment.md'
  - Enemies: './appendices/enemy-compendium.md'
  - Harken's Blessings: './appendices/harkens-blessings.md'
  - Purchase Evaluation: './appendices/purchase-evaluation.md'
  - Purchaseable Skill Books: './appendices/purchaseable-skill-books.md'
  - Respawning Bone Locations: './appendices/respawning-bone-locations.md'
  - Skills and Spells: './appendices/skills-and-spells.md'
