nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss Guides: abyss-guides
  - Adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics
  - Strategies
  - Events
  - Appendices
  - Playing on PC: './emulators/emulators.md'
  - About The Guide: './index.md'
