nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss Guides: abyss-guides
  - Adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics:
      - Character Traits and Stats: './mechanics/traits-and-stats.md'
      - Discipline and Inheritance: './mechanics/discipline-and-inheritance.md'
      - Damage Mechanics: './mechanics/damage-mechanics.md'
      - Trust:
          - Trust Guide: './mechanics/trust/trust.md'
          - Dialogue Chart: './mechanics/trust/chart.md'
  - Strategies:
      - Combat Strategies: './strategies/combat-strategies.md'
      - Farming: './strategies/farming.md'
  - Events:
      - Lamp of Malice:
          - Maps and Text Guide: './events/lamp-of-malice/lamp-of-malice-text-guide.md'
      - Old Castle Ruins:
          - Maps and Text Guide: './events/old-castle-ruins/old-castle-ruins-guide.md'
      - Labyrinth of Fordraig:
          - Maps and Text Guide: './events/labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
      - Pixie and the Secret Garden:
          - Maps and Text Guide: './events/pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
      - Otherworld Adventurers:
          - Maps and Text Guide: './events/otherworld-adventurers/otherworld-adventurers-guide.md'
      - Fighter Proving Grounds:
          - Maps and Text Guide: './events/fighter-proving-grounds/fighter-proving-grounds-guide.md'
  - Appendices
  - Playing on PC: './emulators/emulators.md'
  - About The Guide: './index.md'
