nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss Guides:
      - Introduction: './abyss-guides/0-introduction/index.md'
      - Beginning Abyss:
          - Maps: './abyss-guides/1-beginning-abyss/maps.md'
          - Requests: './abyss-guides/1-beginning-abyss/requests.md'
          - Important Request / Greater Warped One: './abyss-guides/1-beginning-abyss/important-request-gwo.md'
      - Port Town Grand Legion:
          - Maps: './abyss-guides/2-port-town-grand-legion/maps.md'
          - Requests: './abyss-guides/2-port-town-grand-legion/requests.md'
          - Important Request / Greater Warped One: './abyss-guides/2-port-town-grand-legion/important-request-gwo.md'
      - Guarda Fortress:
          - Maps: './abyss-guides/3-guarda-fortress/maps.md'
          - Requests: './abyss-guides/3-guarda-fortress/requests.md'
          - Important Request / Greater Warped One: './abyss-guides/3-guarda-fortress/important-request-gwo.md'
      - Ancient Mausoleum: './abyss-guides/ancient-mausoleum/maps.md'
      - Dens:
          - Den of Earth: './abyss-guides/dens/den-of-earth.md'
          - Den of Fire: './abyss-guides/dens/den-of-fire.md'
          - Den of Wind: './abyss-guides/dens/den-of-wind.md'
          - Den of Light: './abyss-guides/dens/den-of-light.md'
      - Grade Exams: './abyss-guides/grade-exams/maps.md'
      - Misc Bosses:
          - Morgus, God of Death: './abyss-guides/misc-bosses/morgus-god-of-death.md'
  - Adventurers
  - Adventurer Customization:
      - Adventurer Experience: './adventurer-customization/adventurer-experience.md'
      - Blacksmithing: './adventurer-customization/blacksmithing/index.md'
      - Bondmates:
          - Bondmates Quicklist: './adventurer-customization/bondmates/bondmates-quicklist.md'
          - Adventurer Bondmates: './adventurer-customization/bondmates/adventurer-bondmates.md'
          - Bondmates Farming: './adventurer-customization/bondmates/bondmates-farming.md'
          - Beginning Abyss: './adventurer-customization/bondmates/beginning-abyss/bondmates.md'
          - Port Town Grand Legion: './adventurer-customization/bondmates/port-town-grand-legion/bondmates.md'
          - Guarda Fortress: './adventurer-customization/bondmates/guarda-fortress/bondmates.md'
      - Contracts: './adventurer-customization/contracts.md'
      - Party Construction: './adventurer-customization/party-construction.md'
      - Well of the Mind: './adventurer-customization/well-of-the-mind.md'
  - Mechanics:
      - Character Traits and Stats: './mechanics/traits-and-stats.md'
      - Discipline and Inheritance: './mechanics/discipline-and-inheritance.md'
      - Damage Mechanics: './mechanics/damage-mechanics.md'
      - Trust:
          - Trust Guide: './mechanics/trust/trust.md'
          - Dialogue Chart: './mechanics/trust/chart.md'
  - Strategies:
      - Combat Strategies: './strategies/combat-strategies.md'
      - Farming: './strategies/farming.md'
  - Events:
      - Lamp of Malice:
          - Maps and Text Guide: './events/lamp-of-malice/lamp-of-malice-text-guide.md'
      - Old Castle Ruins:
          - Maps and Text Guide: './events/old-castle-ruins/old-castle-ruins-guide.md'
      - Labyrinth of Fordraig:
          - Maps and Text Guide: './events/labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
      - Pixie and the Secret Garden:
          - Maps and Text Guide: './events/pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
      - Otherworld Adventurers:
          - Maps and Text Guide: './events/otherworld-adventurers/otherworld-adventurers-guide.md'
      - Fighter Proving Grounds:
          - Maps and Text Guide: './events/fighter-proving-grounds/fighter-proving-grounds-guide.md'
  - Appendices:
      - Achievements: './appendices/achievements.md'
      - Cursed Wheel Causality:
          - Beginning Abyss: './appendices/wheel-causality/beginning-abyss.md'
          - Port Town Grand Legion: './appendices/wheel-causality/port-town-grand-legion.md'
          - Guarda Fortress: './appendices/wheel-causality/guarda-fortress.md'
      - Dispatches: './appendices/dispatches.md'
      - Equipment:
          - Weapon Types: './appendices/equipment/weapon-types.md'
          - Unique Equipment: './appendices/equipment/unique-equipment.md'
      - Enemies: './appendices/enemy-compendium.md'
      - Harken's Blessings: './appendices/harkens-blessings.md'
      - Purchase Evaluation: './appendices/purchase-evaluation.md'
      - Purchaseable Skill Books: './appendices/purchaseable-skill-books.md'
      - Respawning Bone Locations: './appendices/respawning-bone-locations.md'
      - Skills and Spells: './appendices/skills-and-spells.md'
  - Playing on PC: './emulators/emulators.md'
  - About The Guide: './index.md'
