nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss Guides: abyss-guides
  - Adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics
  - Strategies:
      - Combat Strategies: './strategies/combat-strategies.md'
      - Farming: './strategies/farming.md'
  - Events
  - Appendices
  - Playing on PC: './emulators/emulators.md'
  - About The Guide: './index.md'
