nav:
  - Adventurer Experience: './adventurer-customization/adventurer-experience.md'
  - Blacksmithing: './adventurer-customization/blacksmithing/index.md'
  - Bondmates:
      - Bondmates Quicklist: './adventurer-customization/bondmates/bondmates-quicklist.md'
      - Adventurer Bondmates: './adventurer-customization/bondmates/adventurer-bondmates.md'
      - Bondmates Farming: './adventurer-customization/bondmates/bondmates-farming.md'
      - Beginning Abyss: './adventurer-customization/bondmates/beginning-abyss/bondmates.md'
      - Port Town Grand Legion: './adventurer-customization/bondmates/port-town-grand-legion/bondmates.md'
      - Guarda Fortress: './adventurer-customization/bondmates/guarda-fortress/bondmates.md'
  - Contracts: './adventurer-customization/contracts.md'
  - Party Construction: './adventurer-customization/party-construction.md'
  - Well of the Mind: './adventurer-customization/well-of-the-mind.md'
